# -*- coding: utf-8 -*-
"""109021153_Man Sze Lam_Data Science Project-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTJTorNdvYUP0YRrgOzk8CLFHRza7cs-
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
mypd=pd.read_csv('作業一資料(2).csv')
mypd

mypd = mypd.iloc[:731,0:26] #因為多了一列，所以這邊要改成mypd.iloc[:731,0:26]
mypd

#因為columns如果有括號之類的特殊符號，所以我把columns先改成沒有括號的樣子
mypd.columns = ['編號','性別','出生日數','懷孕周數','出生體重','耐受分數1','耐受分數5','生產發燒','絨毛羊膜炎','死亡','使用導管','PH',
                      'PaCO2','PaO2','BE','WBC','HB','platelet','CRP','Na','K','Ca','D_Bilirubin','creatinine','ALT','敗血症']
mypd

"""##第一題

###把na改成nan(因為na無法用isna偵測)
"""

#先嘗試這段程式可不可以使用索引找出欄位名稱(後面迴圈需要)
print(mypd.columns[0])

import numpy as np
work = np.nonzero(np.array(mypd=='na')) #把mypd中所有值為na的位置找出來，然後用work存起來
work = np.array(work) #把work改成array的形式，因為我後面要轉成list來做迴圈
print(work.shape) 
work

work1 = work.tolist() #work等於work轉成列表
for a in range(0,len(work[0])): #for a in range(0,work[0]的數量)
  number1 = int(work[0][a]) #number1等於work[0][a]，這樣就能知道值為na的位置他的index
  number2 = mypd.columns[work[1][a]] #number1等於work[0][a]，這樣就能知道值為na的位置他的columns，像第一圈number2會是'出生日數'，這樣後面才能用loc更改數值
  #print(number1)
  #print(number2)
  mypd.loc[number1,number2]=np.nan #利用loc把值為na的位置改成NaN，這樣後面才能用isna()計數
mypd

"""###統計欄位缺值"""

#import numpy as np
#mypd.loc[mypd.出生日數=='na','出生日數']=np.nan
#mypd.loc[mypd.使用導管=='na','使用導管']=np.nan
#mypd.loc[mypd.使用導管=='na','使用導管']=np.nan

#print(np.count_nonzero(mypd.編號.isna())) #如果有缺失的欄位isnull會等於True，所以可以用nonzero來計算
#print(np.count_nonzero(mypd.iloc[:,1:2].isna())) #因為性別那欄文字比較特殊，所以直接用iloc選取欄位比較快
#print(np.count_nonzero(mypd.iloc[:,2:3].isna())) #na用isna沒辦法計數
#print(np.count_nonzero(mypd.iloc[:,2:3]=='na'))  #出生日數
#print(np.count_nonzero(mypd.iloc[:,10:11]=='na')+np.count_nonzero(mypd.iloc[:,10:11].isna()))

#import numpy as np
#print(np.count_nonzero(mypd.編號.isna()))
#print(np.count_nonzero(mypd.性別.isna()))
#print(np.count_nonzero(mypd.出生日數.isna()))
#print(np.count_nonzero(mypd.使用導管.isna()))

for a in range(len(mypd.columns)): #for a in range(欄位的數量)
  print(f'欄位{a+1}-{mypd.columns[a]}的缺值筆數為:{np.count_nonzero(mypd.iloc[:,a:a+1].isna())}')
  #用np.count_nonzero(mypd.iloc[:,a:a+1].isna())來計數
  #mypd.iloc[:,a:a+1].isna()可以計算每個欄位的全部資料為nan的是nan的話就會等於True(1)，所以可以用np.count_nonzero來計算有幾個nan

"""#第二題(異常值)"""

import matplotlib.pyplot as plt
boxplot = mypd.boxplot(column=['出生體重'])
plt.show()
plt.close()

"""#懷孕周數(待處理)"""

print(type(mypd.loc[1,'懷孕周數']))

workpd=mypd
print(type(workpd.loc[1,'懷孕周數']))

days=mypd.懷孕周數.values.tolist()
print(days)
print(type(days[1]))

days2 = days
number=-1
for a in days2:
  number+=1
  for b in str(a):
    print(b)
    if b=='+':
      print(days[number])
      if days[number][-1]!='0' and int(days[number][-1]) < 5:
        workpd.loc[number,'懷孕周數']=int(days[number][0:2])
      elif int(days[number][-1]) >= 5:
        workpd.loc[number,'懷孕周數']=1+int(days[number][0:2])
      else:
        continue
      


    else:
      continue

days2 = days
number=-1
for a in days2:
  number+=1
  for b in str(a):
    print(b)
    if b=='+':
      print(days[number])
      if days[number][-1]!='0':
        print(number)
        if int(days[number][-1]) < 5:
          workpd.loc[number,'懷孕周數']=int(days[number][0:2])
        elif int(days[number][-1]) >= 5:
          workpd.loc[number,'懷孕周數']=1+int(days[number][0:2])

      else:
        continue

    else:
      continue

workpd

"""#第四題"""

mypd

print(f'性別為1的筆數有:{np.count_nonzero(mypd.iloc[:,1:2]==1)}筆')
print(f'性別為0的筆數有:{np.count_nonzero(mypd.iloc[:,1:2]==0)}筆')
print(f'絨毛羊膜炎為0的筆數有:{np.count_nonzero(mypd.iloc[:,8:9]==0)}筆')
print(f'絨毛羊膜炎為1的筆數有:{np.count_nonzero(mypd.iloc[:,8:9]==1)}筆')

mypd.iloc[:,8:9]

print(np.count_nonzero(mypd.iloc[:,7:8]==1))

mypd.iloc[:,7:8]

"""第五題

"""

import pandas as pd
import numpy as np

mypd.mean()

np.var(mypd)

mypd.median()

mypd.quantile()

mypd.quantile(0.25)

mypd.quantile(0.75)

from scipy import stats

stats.mode(mypd)
