# -*- coding: utf-8 -*-
"""db01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fO1QzDFES1tnewhOhgufucn1xTOB_IOZ
"""

#Upload to Google Colab

from google.colab import files
uploaded = files.upload()

#pandas
#numpy

import pandas as pd

ImmigrationInfoTW=pd.read_csv('mfy21-i5nso.csv')
ImmigrationInfoTW

ImmigrationInfoTW=ImmigrationInfoTW.iloc[:49,0:45]
ImmigrationInfoTW

ImmigrationInfoTW.column=['時間','國立故宮博物院','市立美術館','國民革命忠烈祠','國立歷史博物館','國立臺灣科學教育館','國立臺灣藝術教育館','市立動物園','市立天文科學教育館',
                          '國立國父紀念館','士林官邸公園','陽明公園','國立中正紀念堂','臺北自來水園區','艋舺龍山寺','關渡自然公園','臺北當代藝術館','北投溫泉博物館',
                          '臺北故事館','台北探索館','凱達格蘭文化館','臺北101觀景台','美麗華摩天輪','臺北市孔廟','林安泰古厝','梅庭','大龍峒保安宮','台北霞海城隍廟','西門紅樓',
                          '草山行館','寶藏巖','芝山文化生態綠園','兒童新樂園','華山1914文化創意產業園區','國立臺灣博物館','松山文創園區','台北植物園','白石湖吊橋',
                          '北投公園露天溫泉浴池','信義公民會館','台北國際藝術村','臺北市電影主題公園','糖廍文化園區','新芳春茶行','新北投車站']
ImmigrationInfoTW
print(ImmigrationInfoTW.column[0:45])

ImmigrationInfoTW.column[1]

print(ImmigrationInfoTW.column[1:45])

ImmigrationInfoTW.row=['時間','2016/1/1','2016/2/1','2016/3/1','2016/4/1','2016/5/1','2016/6/1','2016/7/1','2016/8/1','2016/9/1',
                       '2016/10/1','2016/11/1','2016/12/1','2017/1/1','2017/2/1','2017/3/1','2017/4/1','2017/5/1','2017/6/1',
                       '2017/7/1','2017/8/1','2017/9/1','2017/10/1','2017/11/1','2017/12/1','2018/1/1','2018/2/1','2018/3/1',
                       '2018/4/1','2018/5/1','2018/6/1','2018/7/1','2018/8/1','2018/9/1','2018/10/1','2018/11/1','2018/12/1',
                       '2019/1/1','2019/2/1','2019/3/1','2019/4/1','2019/5/1','2019/6/1','2019/7/1','2019/8/1','2019/9/1','2019/10/1','2019/11/1','2019/12/1']

print(ImmigrationInfoTW.row[1:49])

year_2016=ImmigrationInfoTW.row[1:13]

print(year_2016)

year_2017=ImmigrationInfoTW.row[14:25]

print(year_2017)

year_2018=ImmigrationInfoTW.row[26:37]

print(year_2018)

year_2019=ImmigrationInfoTW.row[38:49]

print(year_2019)